server:
  servlet:
    context-path: /api/v1
  port: 4023

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: mqadmin
    password: admin
    routingKey: my.queue.key
    exchange: mu_queue_exchange